SerieBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: SerieBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 25
        password:
            type: string
            length: 64
        email:
            type: string
            length: 60
            unique: true
        picture:
            type: string
            nullable: true
        isActive:
            name: is_active
            type: boolean
    lifecycleCallbacks: {  }
