# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
            SerieBundle\Entity\User:
                algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        our_db_provider:
            entity:
                class: SerieBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        series:
            pattern: ^/serie/
            guard:
                authenticators:
                    - app.jwt_token_authenticator

        loggedin:
            pattern: ^/user/loggedin
            guard:
                authenticators:
                    - app.jwt_token_authenticator


        # Here you handle regular form authentication
        main:
            anonymous: ~
            logout:
                path:   /user/logout
                target: /

    access_control:
        - { path: ^/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/picture, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/loggedin, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/user, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/profil, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/profiledit, roles: IS_AUTHENTICATED_FULLY }

