episode_show:
    path:     /show/{id}
    defaults: { _controller: "SerieBundle:Episode:getOne" }
    methods:  GET

episode_edit:
    path:     /edit
    defaults: { _controller: "SerieBundle:Episode:edit" }
    methods:  PUT

episode_delete:
    path:     /delete/{id}
    defaults: { _controller: "SerieBundle:Episode:delete" }
    methods:  DELETE

episode_watched:
    path:     /watch
    defaults: { _controller: "SerieBundle:Episode:watch" }
    methods:  POST

episode_getAllBySeason:
    path:     /getbyseason/{id}/{user}/{saison}
    defaults: { _controller: "SerieBundle:Episode:getAllBySeason" }
    methods:  GET


episode_didiwatch:
    path:     /didiwatch/{id}/{episode}/{user}
    defaults: { _controller: "SerieBundle:Episode:didiwatch" }
    methods:  GET

episode_index:
    path:     /{id}/{user}
    defaults: { _controller: "SerieBundle:Episode:getAll" }
    methods:  GET

episode_getLastWatched:
    path:     /getlast/{id}/{user}
    defaults: { _controller: "SerieBundle:Episode:getLastWatched" }
    methods:  GET