user_index:
    path:     /
    defaults: { _controller: "SerieBundle:User:getAll" }
    methods:  GET

user_show:
    path:     /show/{id}
    defaults: { _controller: "SerieBundle:User:getOne" }
    methods:  GET

user_edit:
    path:     /edit
    defaults: { _controller: "SerieBundle:User:edit" }
    methods:  PUT

user_delete:
    path:     /delete/{id}
    defaults: { _controller: "SerieBundle:User:delete" }
    methods:  DELETE

user_registration:
    path:     /register
    defaults: { _controller: "SerieBundle:User:register" }
    methods:  POST

user_image:
    path:     /picture
    defaults: { _controller: "SerieBundle:User:retrieve" }
    methods:  POST

user_login:
    path:     /login
    defaults: { _controller: "SerieBundle:User:login" }
    methods:  POST

user_loggedin:
    path:     /loggedin
    defaults: { _controller: "SerieBundle:User:loggedin" }
    methods:  GET

user_logout:
    path:     /logout
    defaults: { _controller: "SerieBundle:User:logout" }

user_stats:
    path:     /stats/{id}
    defaults: { _controller: "SerieBundle:User:stats" }
    methods:  GET

user_deactivate:
    path:     /deactivate
    defaults: { _controller: "SerieBundle:User:deactivate" }
    methods:  PUT

user_reactivate:
    path:     /reactivate
    defaults: { _controller: "SerieBundle:User:reactivate" }
    methods:  POST